[package]
name = "rust-hyperscan-test"
version = "0.1.0"
authors = ["Matthew Collier <mcollier@digitalbazaar.com>"]
edition = "2018"

[dependencies]
hyperscan = { path = "../rust-hyperscan/hyperscan", features = ["chimera"] }
lazy_static = "1.4.0"
regex = "1"
